region                  = "eu-west-1"
profile_name            = "scrafter"
static_site_bucket_name = "fast-resources-search"
index_document_name     = "index.html"
base_dir                = "../site"
search_lambda_path      = "../search_lambda/lambda_function.py"